### PR TITLE
rewrite and fix query generator for combination operator

### LINKED ISSUE #3771: composer query format compilation fails
A query like the following fails compilation when starting up the business network app:
```
query selectOrdersForProvisioning {
  description: "Select orders ready for provisioning"
  statement:
      SELECT com.biznet.sre.Order
      WHERE (status != 'CANCELLED' AND status != 'RESERVED_IP')
}
```
fails with this error:
running start.js
TypeError: Cannot redefine property: $ne
    at Function.defineProperty (<anonymous>)
    at QueryCompiler.visitArrayCombinationOperator (/usr/local/src/node_modules/composer-runtime/lib/querycompiler.js:549:36)
    at QueryCompiler.visitBinaryExpression (/usr/local/src/node_modules/composer-runtime/lib/querycompiler.js:477:27)
    at QueryCompiler.visit (/usr/local/src/node_modules/composer-runtime/lib/querycompiler.js:84:27)
    at QueryCompiler.visitWhere (/usr/local/src/node_modules/composer-runtime/lib/querycompiler.js:351:31)
    at QueryCompiler.visit (/usr/local/src/node_modules/composer-runtime/lib/querycompiler.js:76:27)
    at Where.accept (/usr/local/src/node_modules/composer-common/lib/query/where.js:55:24)
    at QueryCompiler.visitSelect (/usr/local/src/node_modules/composer-runtime/lib/querycompiler.js:300:42)
    at QueryCompiler.visit (/usr/local/src/node_modules/composer-runtime/lib/querycompiler.js:74:27)
    at Select.accept (/usr/local/src/node_modules/composer-common/lib/query/select.js:58:24)

It appears that multiple NEQ comparisons are not supported for the same field? 

## Expected Behavior
Query should compile

## Possible Fix
If this is not the correct format and a different  format is supported then that format and examples must be documented and then the issue can be closed, otherwise the query compiler needs to support multiple NEQ comparisons on the same field.

## Context
This is a limitation in how I can query effectively and therefore requiring inefficient workarounds.

## Your Environment
* Version used: composer 0.19.0, fabric 1.1
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

### PR DESCRIPTION
**Pull request by andrew-coleman**
The implementation of the combination operator in the query compiler has evolved in response to various past issues.  Now is a good time to revisit the underlying algorithm and re-implement the logic.  This also resolves #3771 

Signed-off-by: andrew-coleman <andrew_coleman@uk.ibm.com>

## Checklist
 - [ ]  A link to the issue/user story that the pull request relates to
 - [ ]  How to recreate the problem without the fix
 - [ ]  Design of the fix
 - [ ]  How to prove that the fix works
 - [ ]  Automated tests that prove the fix keeps on working
 - [ ]  Documentation - any JSDoc, website, or Stackoverflow answers?

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-composer)
- [ ] [GitHub Issues](https://github.com/hyperledger/composer/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/composer)

### CODE REVIEW

File: packages/composer-runtime/lib/querycompiler.js [hunk 1]
```diff
@@ -515,57 +515,38 @@ class QueryCompiler {
         let left = this.visit(ast.left, parameters);
         let right = this.visit(ast.right, parameters);
 
-        // Build the Mango selector for this operator.
```
Comment (sstone1) [inline packages/composer-runtime/lib/querycompiler.js]: 😍 at all this deleted code
