### PR TITLE
change in process of install git

### LINKED ISSUE #1750: Wrong version of Git installed using prereqs-ubuntu.sh
## Context
In Installing and developing with Hyperledger Composer under [Before you begin](https://github.com/hyperledger/composer/blob/master/packages/composer-website/jekylldocs/installing/development-tools.md#before-you-begin), the prerequisite for git is specified as 2.9.x, but prereqs-ubuntu.sh installs 2.7.x on ubuntu 16.04.

## Expected Behavior
prereqs-ubuntu.sh should install git version 2.9.x

## Actual Behavior
Git version 2.7.x is installed

## Possible Fix
Changes in process of getting git

## Steps to Reproduce

1. curl -O https://hyperledger.github.io/composer/prereqs-ubuntu.sh
2. chmod u+x prereqs-ubuntu.sh
3. ./prereqs-ubuntu.sh

## Existing issues
There is no existing issue

## Context
The version of git provided in documentation as prerequisite and the version installed are different

## Your Environment
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

### PR DESCRIPTION
**Pull request by aviralwal**
closes #1750

### CODE REVIEW

**Comment by caroline-church** [comment]
@davidkel can you review this please?

**Comment by aviralwal** [comment]
The documentation has suggested git 2.9.x version.  Documentation should have required git version as >=2.9.0 so that it is clear any version(including latest) above 2.9.0 is fine.

**Comment by davidkel** [comment]
Yep the documentation should be changed as well. In fact there is no requirement for it to be 2.9.x I think that got put in there because whoever ran the original script to provide doc was using 2.9.x so please feel free to modify the doc as well.

**Comment by aviralwal** [comment]
Is there any requirement for minimum version of git required for the composer?

**Comment by aviralwal** [comment]
Please review the change for [git install](https://github.com/hyperledger/composer/pull/1753/commits/3ce6a018982697252406e39f3de0513bd746e66e)

File: packages/composer-website/jekylldocs/prereqs-ubuntu.sh [hunk 1]
```diff
@@ -35,8 +35,10 @@ echo "# Updating package lists"
 sudo apt-get update
 
 # Install Git
-echo "# Installing GitHub"
-sudo apt-get -y install git
+echo "# Installing Git"
```
Comment (davidkel) [inline packages/composer-website/jekylldocs/prereqs-ubuntu.sh]: Would recommend putting sudo apt-add-repository ppa:git-core/ppa before the apt-get update above (line 35) so only need to call apt-get update once. Also add a -y to the apt-add-repository command because I have seen it prompt you to ask if you want to do this.

Comment (davidkel) [inline packages/composer-website/jekylldocs/prereqs-ubuntu.sh]: Would recommend putting sudo apt-add-repository ppa:git-core/ppa before the apt-get update above (line 35) so only need to call apt-get update once. Also add a -y to the apt-add-repository command because I have seen it prompt you to ask if you want to do this.

File: packages/composer-website/jekylldocs/prereqs-ubuntu.sh [hunk 2]
```diff
@@ -32,12 +32,11 @@ fi
 
 # Update package lists
 echo "# Updating package lists"
+sudo apt-add-repository -y ppa:git-core/ppa
```
Comment (aviralwal) [inline packages/composer-website/jekylldocs/prereqs-ubuntu.sh]: Shifted sudo apt-add-repository ppa:git-core/ppa aboveapt update and added -y for no prompt
